# Generated by Django 3.2.18 on 2023-02-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0004_alter_tests_finished_at_alter_tests_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='questions_count',
            field=models.IntegerField(default=0),
        ),
    ]
