# Generated by Django 4.1.6 on 2023-02-12 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainQuizApp', '0002_alter_uploadedfile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_finished', models.BooleanField(default=False)),
                ('finished_at', models.DateTimeField(blank=True)),
                ('question_count', models.IntegerField()),
                ('result', models.IntegerField(blank=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainQuizApp.uploadedfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Лог тестов',
                'verbose_name_plural': 'Логи тестов',
                'ordering': ['started_at'],
            },
        ),
    ]
