# Generated by Django 3.2.18 on 2023-02-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0005_uploadedfile_questions_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test',
            field=models.TextField(default='test'),
        ),
    ]
