# Generated by Django 3.2.18 on 2023-02-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0006_tests_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='test_array',
            field=models.JSONField(default=list),
        ),
    ]
