# Generated by Django 3.2.18 on 2023-02-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0007_tests_test_array'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='test',
        ),
    ]
