# Generated by Django 3.2.18 on 2023-02-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0008_remove_tests_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests',
            name='test_array',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
