# Generated by Django 4.1.6 on 2023-02-12 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'Загруженный файл', 'verbose_name_plural': 'Загруженные файлы'},
        ),
    ]
