# Generated by Django 3.2.18 on 2023-02-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='user_answers_array',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
