# Generated by Django 3.2.18 on 2023-02-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainQuizApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='my_dict_array',
        ),
    ]
